"""initial schema

Revision ID: ab9bb0885648
Revises: 
Create Date: 2026-08-18 15:33:31.240127

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab9bb0885648'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # player_vectors.embedding needs pgvector; the extension must exist first.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_tr', sa.String(length=120), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_countries'))
    )
    op.create_table('ingest_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rows_written', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_runs'))
    )
    op.create_table('shortlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shortlists'))
    )
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('strength_coef', sa.Float(), nullable=True),
    sa.Column('api_football_id', sa.Integer(), nullable=True),
    sa.Column('fbref_id', sa.String(length=64), nullable=True),
    sa.Column('transfermarkt_id', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], name=op.f('fk_leagues_country_code_countries'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leagues')),
    sa.UniqueConstraint('api_football_id', name=op.f('uq_leagues_api_football_id')),
    sa.UniqueConstraint('transfermarkt_id', name=op.f('uq_leagues_transfermarkt_id'))
    )
    op.create_index('ix_leagues_country_tier', 'leagues', ['country_code', 'tier'], unique=False)
    op.create_table('clubs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('transfermarkt_id', sa.BigInteger(), nullable=True),
    sa.Column('api_football_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_clubs_league_id_leagues'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clubs')),
    sa.UniqueConstraint('api_football_id', name=op.f('uq_clubs_api_football_id')),
    sa.UniqueConstraint('transfermarkt_id', name=op.f('uq_clubs_transfermarkt_id'))
    )
    op.create_index('ix_clubs_league', 'clubs', ['league_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('nationality_code', sa.String(length=2), nullable=True),
    sa.Column('position', sa.String(length=40), nullable=True),
    sa.Column('sub_position', sa.String(length=60), nullable=True),
    sa.Column('foot', sa.String(length=10), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('current_club_id', sa.BigInteger(), nullable=True),
    sa.Column('market_value_eur', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('contract_until', sa.Date(), nullable=True),
    sa.Column('transfermarkt_id', sa.BigInteger(), nullable=True),
    sa.Column('fbref_id', sa.String(length=32), nullable=True),
    sa.Column('api_football_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_club_id'], ['clubs.id'], name=op.f('fk_players_current_club_id_clubs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nationality_code'], ['countries.code'], name=op.f('fk_players_nationality_code_countries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('api_football_id', name=op.f('uq_players_api_football_id')),
    sa.UniqueConstraint('fbref_id', name=op.f('uq_players_fbref_id')),
    sa.UniqueConstraint('transfermarkt_id', name=op.f('uq_players_transfermarkt_id'))
    )
    op.create_index('ix_players_birth_date', 'players', ['birth_date'], unique=False)
    op.create_index('ix_players_current_club', 'players', ['current_club_id'], unique=False)
    op.create_index('ix_players_full_name', 'players', ['full_name'], unique=False)
    op.create_table('market_value_history',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_market_value_history_player_id_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'date', name=op.f('pk_market_value_history'))
    )
    op.create_table('player_season_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.String(length=9), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('club_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('matches', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('xa', sa.Float(), nullable=True),
    sa.Column('key_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_player_season_stats_club_id_clubs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_player_season_stats_league_id_leagues'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_season_stats_player_id_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_season_stats')),
    sa.UniqueConstraint('player_id', 'season', 'club_id', 'source', name='uq_player_season_source')
    )
    op.create_index('ix_player_season_stats_season_league', 'player_season_stats', ['season', 'league_id'], unique=False)
    op.create_table('player_vectors',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.String(length=9), nullable=False),
    sa.Column('position_group', sa.String(length=2), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=64), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_vectors_player_id_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'season', 'position_group', name=op.f('pk_player_vectors'))
    )
    op.create_table('shortlist_players',
    sa.Column('shortlist_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_shortlist_players_player_id_players'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shortlist_id'], ['shortlists.id'], name=op.f('fk_shortlist_players_shortlist_id_shortlists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shortlist_id', 'player_id', name=op.f('pk_shortlist_players'))
    )
    op.create_table('transfers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('from_club_id', sa.BigInteger(), nullable=True),
    sa.Column('to_club_id', sa.BigInteger(), nullable=True),
    sa.Column('transfer_date', sa.Date(), nullable=True),
    sa.Column('fee_eur', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('season', sa.String(length=9), nullable=True),
    sa.ForeignKeyConstraint(['from_club_id'], ['clubs.id'], name=op.f('fk_transfers_from_club_id_clubs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_transfers_player_id_players'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_club_id'], ['clubs.id'], name=op.f('fk_transfers_to_club_id_clubs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfers'))
    )
    op.create_index('ix_transfers_player', 'transfers', ['player_id'], unique=False)
    op.create_index('ix_transfers_season', 'transfers', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    The `vector` extension is intentionally left installed: dropping it is a
    database-wide action that could break anything else sharing this database.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transfers_season', table_name='transfers')
    op.drop_index('ix_transfers_player', table_name='transfers')
    op.drop_table('transfers')
    op.drop_table('shortlist_players')
    op.drop_table('player_vectors')
    op.drop_index('ix_player_season_stats_season_league', table_name='player_season_stats')
    op.drop_table('player_season_stats')
    op.drop_table('market_value_history')
    op.drop_index('ix_players_full_name', table_name='players')
    op.drop_index('ix_players_current_club', table_name='players')
    op.drop_index('ix_players_birth_date', table_name='players')
    op.drop_table('players')
    op.drop_index('ix_clubs_league', table_name='clubs')
    op.drop_table('clubs')
    op.drop_index('ix_leagues_country_tier', table_name='leagues')
    op.drop_table('leagues')
    op.drop_table('shortlists')
    op.drop_table('ingest_runs')
    op.drop_table('countries')
    # ### end Alembic commands ###
