"""match level data and wider league coverage

Revision ID: fc8896d30ac1
Revises: 8332639e4da5
Create Date: 2026-08-19 02:22:25.751710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc8896d30ac1'
down_revision: Union[str, Sequence[str], None] = '8332639e4da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=9), nullable=True),
    sa.Column('round', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('home_club_id', sa.BigInteger(), nullable=True),
    sa.Column('away_club_id', sa.BigInteger(), nullable=True),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('home_formation', sa.String(length=32), nullable=True),
    sa.Column('away_formation', sa.String(length=32), nullable=True),
    sa.Column('stadium', sa.String(length=160), nullable=True),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('referee', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['away_club_id'], ['clubs.id'], name=op.f('fk_matches_away_club_id_clubs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['home_club_id'], ['clubs.id'], name=op.f('fk_matches_home_club_id_clubs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_matches_league_id_leagues'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    op.create_index('ix_matches_date', 'matches', ['date'], unique=False)
    op.create_index('ix_matches_league_season', 'matches', ['league_id', 'season'], unique=False)
    op.create_table('player_match_stats',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=True),
    sa.Column('played_on', sa.Date(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_player_match_stats_club_id_clubs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_player_match_stats_match_id_matches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_match_stats_player_id_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'match_id', name=op.f('pk_player_match_stats'))
    )
    op.create_index('ix_player_match_stats_club', 'player_match_stats', ['club_id'], unique=False)
    op.create_index('ix_player_match_stats_player_date', 'player_match_stats', ['player_id', 'played_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_match_stats_player_date', table_name='player_match_stats')
    op.drop_index('ix_player_match_stats_club', table_name='player_match_stats')
    op.drop_table('player_match_stats')
    op.drop_index('ix_matches_league_season', table_name='matches')
    op.drop_index('ix_matches_date', table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
