"""shot events

Revision ID: 9c4f5150ea43
Revises: fc8896d30ac1
Create Date: 2026-08-19 12:55:24.073391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c4f5150ea43'
down_revision: Union[str, Sequence[str], None] = 'fc8896d30ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shots',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.BigInteger(), nullable=True),
    sa.Column('season', sa.String(length=9), nullable=True),
    sa.Column('played_on', sa.Date(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('location_x', sa.Float(), nullable=True),
    sa.Column('location_y', sa.Float(), nullable=True),
    sa.Column('body_part', sa.String(length=32), nullable=True),
    sa.Column('situation', sa.String(length=32), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('is_goal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_shots_club_id_clubs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_shots_league_id_leagues'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_shots_match_id_matches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_shots_player_id_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shots'))
    )
    op.create_index('ix_shots_league_season', 'shots', ['league_id', 'season'], unique=False)
    op.create_index('ix_shots_player_date', 'shots', ['player_id', 'played_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shots_player_date', table_name='shots')
    op.drop_index('ix_shots_league_season', table_name='shots')
    op.drop_table('shots')
    # ### end Alembic commands ###
