"""image and logo urls

Revision ID: 5d2a189e1dd8
Revises: 9c4f5150ea43
Create Date: 2026-08-19 14:28:12.927133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2a189e1dd8'
down_revision: Union[str, Sequence[str], None] = '9c4f5150ea43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('leagues', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('players', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'image_url')
    op.drop_column('leagues', 'logo_url')
    op.drop_column('clubs', 'logo_url')
    # ### end Alembic commands ###
