"""player last season

Revision ID: 0b0ed27b211b
Revises: 5d2a189e1dd8
Create Date: 2026-08-19 15:24:05.104394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b0ed27b211b'
down_revision: Union[str, Sequence[str], None] = '5d2a189e1dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('last_season', sa.String(length=9), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'last_season')
    # ### end Alembic commands ###
