"""player season metrics

Revision ID: 6d3d5b10da07
Revises: 0b0ed27b211b
Create Date: 2026-08-19 17:43:43.660885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d3d5b10da07'
down_revision: Union[str, Sequence[str], None] = '0b0ed27b211b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_season_metrics',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.String(length=9), nullable=False),
    sa.Column('position_group', sa.String(length=2), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('club_id', sa.BigInteger(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('per90', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('zscore', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('percentile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sample_size', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_player_season_metrics_club_id_clubs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_player_season_metrics_league_id_leagues'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_season_metrics_player_id_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'season', 'position_group', name=op.f('pk_player_season_metrics'))
    )
    op.create_index('ix_metrics_league', 'player_season_metrics', ['league_id'], unique=False)
    op.create_index('ix_metrics_season_group', 'player_season_metrics', ['season', 'position_group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metrics_season_group', table_name='player_season_metrics')
    op.drop_index('ix_metrics_league', table_name='player_season_metrics')
    op.drop_table('player_season_metrics')
    # ### end Alembic commands ###
