/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/globe/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Globe icin tek istekte ozet */
        get: operations["globe_summary_globe_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ligleri listele */
        get: operations["list_leagues_leagues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{league_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lig detayi ve kulupleri */
        get: operations["get_league_leagues__league_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clubs/{club_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kulup detayi ve kadrosu */
        get: operations["get_club_clubs__club_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oyuncu ara ve filtrele */
        get: operations["search_players_players_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{player_id}/form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mac bazli form egrisi ve sezon trendi */
        get: operations["get_player_form_players__player_id__form_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oyuncu profili */
        get: operations["get_player_players__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClubDetail */
        ClubDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Leagueid */
            leagueId?: number | null;
            /** Leaguename */
            leagueName?: string | null;
            /** Countrycode */
            countryCode?: string | null;
            /** Squadseason */
            squadSeason?: string | null;
            /**
             * Squad
             * @default []
             */
            squad: components["schemas"]["PlayerSummary"][];
        };
        /** ClubSummary */
        ClubSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Leagueid */
            leagueId?: number | null;
            /**
             * Squadsize
             * @default 0
             */
            squadSize: number;
        };
        /** CountryOut */
        CountryOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Nametr */
            nameTr?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
        };
        /**
         * FormPoint
         * @description One match, plus the rolling average up to and including it.
         */
        FormPoint: {
            /** Matchid */
            matchId: number;
            /** Playedon */
            playedOn?: string | null;
            /** Clubname */
            clubName?: string | null;
            /** Leaguename */
            leagueName?: string | null;
            /** Opponentname */
            opponentName?: string | null;
            /** Ishome */
            isHome?: boolean | null;
            /** Minutes */
            minutes?: number | null;
            /** Value */
            value?: number | null;
            /** Rolling */
            rolling?: number | null;
        };
        /** FormSeries */
        FormSeries: {
            /** Metric */
            metric: string;
            /** Metriclabel */
            metricLabel: string;
            /** Window */
            window: number;
            /** Totalmatches */
            totalMatches: number;
            /** Points */
            points: components["schemas"]["FormPoint"][];
        };
        /**
         * GlobeLeagueNode
         * @description One league, anchored at its country centroid.
         */
        GlobeLeagueNode: {
            /** Leagueid */
            leagueId: number;
            /** Name */
            name: string;
            /** Countrycode */
            countryCode: string;
            /** Tier */
            tier: number;
            /** Strengthcoef */
            strengthCoef?: number | null;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Season */
            season?: string | null;
            /** Clubcount */
            clubCount: number;
            /** Playercount */
            playerCount: number;
        };
        /** GlobeSummary */
        GlobeSummary: {
            /** Countries */
            countries: components["schemas"]["CountryOut"][];
            /** Leagues */
            leagues: components["schemas"]["GlobeLeagueNode"][];
            /** Arcs */
            arcs: components["schemas"]["GlobeTransferArc"][];
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
        };
        /**
         * GlobeTransferArc
         * @description Aggregated country -> country transfer flow.
         */
        GlobeTransferArc: {
            /** Fromlat */
            fromLat: number;
            /** Fromlng */
            fromLng: number;
            /** Tolat */
            toLat: number;
            /** Tolng */
            toLng: number;
            /** Fromcountry */
            fromCountry: string;
            /** Tocountry */
            toCountry: string;
            /** Transfercount */
            transferCount: number;
            /** Totalfeeeur */
            totalFeeEur?: number | null;
            /** Season */
            season?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Service */
            service: string;
            /** Version */
            version: string;
            /**
             * Database
             * @enum {string}
             */
            database: "up" | "down" | "unknown";
        };
        /** LeagueDetail */
        LeagueDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Countrycode */
            countryCode: string;
            /** Tier */
            tier: number;
            /** Strengthcoef */
            strengthCoef?: number | null;
            /** Season */
            season?: string | null;
            /**
             * Clubcount
             * @default 0
             */
            clubCount: number;
            /**
             * Playercount
             * @default 0
             */
            playerCount: number;
            country?: components["schemas"]["CountryOut"] | null;
            /** Squadseason */
            squadSeason?: string | null;
            /**
             * Clubs
             * @default []
             */
            clubs: components["schemas"]["ClubSummary"][];
        };
        /** LeagueOut */
        LeagueOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Countrycode */
            countryCode: string;
            /** Tier */
            tier: number;
            /** Strengthcoef */
            strengthCoef?: number | null;
            /** Season */
            season?: string | null;
            /**
             * Clubcount
             * @default 0
             */
            clubCount: number;
            /**
             * Playercount
             * @default 0
             */
            playerCount: number;
        };
        /** MarketValuePoint */
        MarketValuePoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Valueeur */
            valueEur: number;
        };
        /** PlayerDetail */
        PlayerDetail: {
            /** Id */
            id: number;
            /** Fullname */
            fullName: string;
            /** Position */
            position?: string | null;
            /** Subposition */
            subPosition?: string | null;
            /** Birthdate */
            birthDate?: string | null;
            /** Age */
            age?: number | null;
            /** Nationalitycode */
            nationalityCode?: string | null;
            /** Clubid */
            clubId?: number | null;
            /** Clubname */
            clubName?: string | null;
            /** Leagueid */
            leagueId?: number | null;
            /** Marketvalueeur */
            marketValueEur?: number | null;
            /** Leaguename */
            leagueName?: string | null;
            /** Foot */
            foot?: string | null;
            /** Heightcm */
            heightCm?: number | null;
            /** Contractuntil */
            contractUntil?: string | null;
            /**
             * Seasonstats
             * @default []
             */
            seasonStats: components["schemas"]["SeasonStatsOut"][];
            /**
             * Marketvaluehistory
             * @default []
             */
            marketValueHistory: components["schemas"]["MarketValuePoint"][];
        };
        /** PlayerForm */
        PlayerForm: {
            /** Playerid */
            playerId: number;
            series: components["schemas"]["FormSeries"];
            /** Seasons */
            seasons: components["schemas"]["SeasonTrendPoint"][];
        };
        /** PlayerSearchResult */
        PlayerSearchResult: {
            /** Items */
            items: components["schemas"]["PlayerSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * PlayerSummary
         * @description Compact shape used in lists, squads and search results.
         */
        PlayerSummary: {
            /** Id */
            id: number;
            /** Fullname */
            fullName: string;
            /** Position */
            position?: string | null;
            /** Subposition */
            subPosition?: string | null;
            /** Birthdate */
            birthDate?: string | null;
            /** Age */
            age?: number | null;
            /** Nationalitycode */
            nationalityCode?: string | null;
            /** Clubid */
            clubId?: number | null;
            /** Clubname */
            clubName?: string | null;
            /** Leagueid */
            leagueId?: number | null;
            /** Marketvalueeur */
            marketValueEur?: number | null;
        };
        /** SeasonStatsOut */
        SeasonStatsOut: {
            /** Season */
            season: string;
            /** Source */
            source: string;
            /** Leagueid */
            leagueId?: number | null;
            /** Clubid */
            clubId?: number | null;
            /** Clubname */
            clubName?: string | null;
            /** Minutes */
            minutes?: number | null;
            /** Matches */
            matches?: number | null;
            /** Goals */
            goals?: number | null;
            /** Assists */
            assists?: number | null;
            /** Xg */
            xg?: number | null;
            /** Xa */
            xa?: number | null;
            /** Goalsper90 */
            goalsPer90?: number | null;
            /** Assistsper90 */
            assistsPer90?: number | null;
            /** Keymetrics */
            keyMetrics?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * SeasonTrendPoint
         * @description Per-season aggregate — the "is he growing" view above the match noise.
         */
        SeasonTrendPoint: {
            /** Season */
            season: string;
            /** Matches */
            matches: number;
            /** Minutes */
            minutes: number;
            /** Minutespermatch */
            minutesPerMatch: number;
            /** Goals */
            goals: number;
            /** Assists */
            assists: number;
            /** Goalsper90 */
            goalsPer90?: number | null;
            /** Assistsper90 */
            assistsPer90?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    globe_summary_globe_summary_get: {
        parameters: {
            query?: {
                /** @description Transfer arc'larini sezona gore filtrele */
                season?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobeSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_leagues_leagues_get: {
        parameters: {
            query?: {
                /** @description ISO ulke kodu */
                country?: string | null;
                tier?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_league_leagues__league_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_club_clubs__club_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                club_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClubDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_players_players_search_get: {
        parameters: {
            query?: {
                /** @description Isim parcasi */
                q?: string | null;
                /** @description Pozisyon veya alt pozisyon */
                position?: string | null;
                league_id?: number | null;
                country?: string | null;
                age_min?: number | null;
                age_max?: number | null;
                /** @description Azami piyasa degeri (EUR) */
                value_max?: number | null;
                /** @description Son sezon asgari dakika */
                minutes_min?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_form_players__player_id__form_get: {
        parameters: {
            query?: {
                /** @description Metrik: minutes, goals, assists, goal_contributions */
                metric?: string;
                /** @description Kayan ortalama penceresi (mac) */
                window?: number;
                /** @description Kac maca bakilacak (en yeniden geriye) */
                limit?: number;
            };
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerForm"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
